eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: test-client
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.entity
  config-location:
    classpath: mybatis/mybatis-config.xml
  mapper-locations:
    classpath: mybatis/mapper/*.xml
